---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: upg-loadme
  namespace: demo
spec:
  # Add hpa spec as per requirement
  # Refer: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#creating-the-autoscaler-declaratively
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: upgloadme
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50